<?php

/**
 * BasePhone_data
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $phone_id
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * 
 * @method integer    getPhoneId()    Returns the current record's "phone_id" value
 * @method integer    getUserId()     Returns the current record's "user_id" value
 * @method string     getFirstName()  Returns the current record's "first_name" value
 * @method string     getLastName()   Returns the current record's "last_name" value
 * @method string     getPhone()      Returns the current record's "phone" value
 * @method Phone_data setPhoneId()    Sets the current record's "phone_id" value
 * @method Phone_data setUserId()     Sets the current record's "user_id" value
 * @method Phone_data setFirstName()  Sets the current record's "first_name" value
 * @method Phone_data setLastName()   Sets the current record's "last_name" value
 * @method Phone_data setPhone()      Sets the current record's "phone" value
 * 
 * @package    test1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhone_data extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('phone_data');
        $this->hasColumn('phone_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}