<?php

/**
 * Phone_data
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    test1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Phone_data extends BasePhone_data
{

}