<?php

/**
 * Phone_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Phone_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Phone_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phone_data');
    }
}