# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }


  

#sfGuard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password } 

 
sf_guard_register:
  url: /user/new
  param: { module: sfApply, action: apply }
  
  
#sfApply

apply:
  url:  /user/new
  param: { module: sfApply, action: apply }
  
reset:
  url:  /user/password-reset
  param: { module: sfApply, action: reset }

resetRequest:
  param: { module: sfApply, action: resetRequest }
  
resetCancel:
  url:  /user/reset-cancel
  param:  { module: sfApply, action: resetCancel }

validate:
  url:  /user/confirm/:validate
  param: { module: sfApply, action: confirm }
  
settings:
  url:  /user/settings
  param: { module: sfApply, action: settings }
#end sfapply
account:
  url: /account
  param: { module: account, action: index }

default:
  url:   /:module/:action/*
    

