<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/04 14:35:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test1',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
