<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/19 16:50:33
$this->security = array (
  'settings' => 
  array (
    'is_secure' => true,
  ),
  'editemail' => 
  array (
    'is_secure' => true,
  ),
  'apply' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
