Phone_data:
  actAs: [Timestampable]
  tableName: phone_data
  columns:
    phone_id:
      type: integer
      primary: true
      autoincrement: true
    user_id:
      type: integer(10)
    first_name:
      type: string(255)
    last_name:
      type: string(255)
    phone:
      type: string(255)
Category:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    name: string(255)